# Generated by Django 4.2.5 on 2023-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('NA', 'Non Allocated'), ('P', 'Pending'), ('C', 'Completed')], max_length=10),
        ),
    ]
